### ISSUE TITLE
AttributeError: 'Model' object has no attribute '_standardize_user_data'

### ISSUE THREAD

**Issue by tom501** [philipperemy/keract#100]
I am getting the following error when I try to call the **get_activations** function after creating and fit my model: 

`return K.function(k_inputs, nodes_to_evaluate)(model._standardize_user_data(x, y))
AttributeError: 'Model' object has no attribute '_standardize_user_data'`

at line 42, in eval_fn (keract.py)
Do you know what can cause it?

I'm using Keras 2.3.1 and Tensorflow 2.2.0

**Comment by tom501** [comment]
I have read this closed issue https://github.com/philipperemy/keract/issues/91 and I downgrade Tensorflow to 2.1.0.

It seems to have fix the problem...

**Comment by philipperemy** [comment]
@tom501 upgrade to the latest keract (>=4.0). It should fix the problem with the latest Keras 2.3.1 and Tensorflow 2.2.0. Let me know!

**Comment by tom501** [comment]
I update keract (4.0.0) and it doesn't give me that error anymore, thanks!

**Comment by philipperemy** [comment]
Great thanks for confirming!
