### ISSUE TITLE
Can this be used for multi label Tabular data?

### ISSUE THREAD

**Issue by Shameendra** [philipperemy/keract#101]
Hi i just was curious if i can use this for multi label tabular data. Since ma table has 1000 columns as input data and target has 19 columns, can anyone explain if keract works? i seem to have no success on my first attempt

**Comment by qwertpi** [comment]
> Hi i just was curious if i can use this for multi label tabular data. Since ma table has 1000 columns as input data and target has 19 columns, can anyone explain if keract works? i seem to have no success on my first attempt

What do you mean by no success? What did you expect to happen? What actually happened?

**Comment by Shameendra** [comment]
So i have input dataset of 1000 columns and output target of 19 columns. so one row of input data would have 19 predictions(1 row, 19 columns). when i try to get activations of lets say just the first column of the prediction, there does not seem to be anything that can do this job. it it always gives me activations for the output layer but but for a specific outout of the output layer.

Some code illustration: 
   `#get keract activations
    keract_inputs = X_test_n[0:1]    #np array
    keract_targets = y_test_n[0:1]   #np array
    activations = get_activations(model, keract_inputs, layer_name= None, nodes_to_evaluate=None, 
    output_format='simple', auto_compile=True)
     `
but my input and output look like this:

    ` keract_inputs = [[ 0.59918982 -0.11407744  0.01111111 ...  0.          1.         0.        ]]
     keract_targets = [[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
    `
So my goal is to get the activations for just the keract_target which has value 1. but it shoes me the activations for the entire keract_target instead. IS there some way to get the activations for just specific outputs columns

**Comment by philipperemy** [comment]
@Shameendra yes you can use https://pypi.org/project/tabulate/ if you want to produce a table from a numpy array.
I'll close this issue but please re-open it if it's not clear.
