### ISSUE TITLE
The newly loaded model cannot find the layer

### ISSUE THREAD

**Issue by Happy-AiLearn** [philipperemy/keract#111]
from tensorflow.keras.models import load_model
model = load_model('./model/model_new_weight_01.hdf5')

attention_map = get_activations(model, [test_data_1, test_data_2], layer_names= 'activation_3')['activation_3']

**KeyError ：**
KeyError: 'Could not find a layer with name: [activation_3]. Network layers are [input_5, input_6, embedding_4, embedding_5, bidirectional_4, bidirectional_5, dense_12, lambda_4, dense_14, lambda_5, dot_8, dot_10, activation_2, activation_3, dot_9, dot_11, concatenate_6, concatenate_7, dense_13, dense_15, concatenate_8, dropout_2, dense_16, dense_17]'

**Comment by philipperemy** [comment]
https://github.com/philipperemy/keras-tcn/blob/23845be7a35bb8bff6fbd8d3ccb5e7e50c9e4884/tasks/save_reload_sequential_model.py#L34
Use `custom_objects={'TCN': TCN}` when using `load_model` in general.
