### ISSUE TITLE
Does this code output feature map learned by cnn? 

### ISSUE THREAD

**Issue by Hessen525** [philipperemy/keract#112]
Hi, @philipperemy 
Thanks for this awesome project! Does this code output feature map learned by cnn? 

![image](https://user-images.githubusercontent.com/25447481/90522791-b8d0de80-e19e-11ea-9031-fc122fc9e665.png)

Both input and output data are sequence data, not graph.

**Comment by philipperemy** [comment]
@Hessen525 hey thanks for the feedback! Much appreciated 👍 

I'm not sure exactly about your example. Keract outputs the activations of each of your model layers.

So when it goes through a CNN (2D) layer, the activation map you get will be of shape `(batch_size, rows, cols, channels)`. And 3D for a CNN 1D.

**Comment by philipperemy** [comment]
I'll close this issue. If you have any other questions please reopen it. Thank you.
