### ISSUE TITLE
Visualization on image sequence

### ISSUE THREAD

**Issue by marteautony** [philipperemy/keract#126]
Hello,

First of all, thank you for this easy-to-learn package.

Is it possible to use this package on models taking image sequences as input?

For example in my case I do action classification with a C3D model on 16 images (None, 112, 112, 16, 3) and the exception "Expect a tensor of 3 or 4 dimensions." kill the visualization.

Have a good day.

Tony

**Comment by philipperemy** [comment]
@marteautony yep definitely possible but will have to define what type of output should be good.

**Comment by philipperemy** [comment]
Closed for inactivity.
