### ISSUE TITLE
get_activations: AttributeError when nested=True

### ISSUE THREAD

**Issue by jvahl** [philipperemy/keract#134]
I have a nested model using a `TimeDistributed` layer. When trying to retrieve activations of a nested layer via `keract.get_activations`, I get an AttributeError. Here's a simple example:

```python
import tensorflow as tf
import keract
import numpy as np

# define model for each time step
input_time = tf.keras.Input(shape=(None,),name='input_time')
emb = tf.keras.layers.Embedding(10,4,name='embedding')(input_time)
lstm = tf.keras.layers.LSTM(4, name='lstm')(emb)
output_time = tf.keras.layers.Dense(1,name='output_time')(lstm)

model_time = tf.keras.Model(input_time,output_time)
print(model_time.summary())

# define full model
input = tf.keras.Input(shape=(None,None),name='input')
timesteps = tf.keras.layers.TimeDistributed(model_time,name='timedistributed')(input)
output = tf.keras.layers.Dense(1)(timesteps)

model = tf.keras.Model(input,output)
print(model.summary())

# create example
x = np.array([[[1,2,1]],[[3,4,5]]])
print(model.predict(x))

# get activations
act = keract.get_activations(model, x, layer_names='embedding',nested=True)
print(act)
```

Which raised

```python
AttributeError                            Traceback (most recent call last)

/usr/local/lib/python3.6/dist-packages/keract/keract.py in _get_nodes(module, output_format, nested, layer_names)
    211                     continue
--> 212                 key = n_(m.output, output_format_=output_format, nested=nested)
    213             except AttributeError:  # for example Sequential. After tf2.3.

AttributeError: 'ListWrapper' object has no attribute 'output'


During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)

5 frames

/usr/local/lib/python3.6/dist-packages/keract/keract.py in _get_nodes(module, output_format, nested, layer_names)
    212                 key = n_(m.output, output_format_=output_format, nested=nested)
    213             except AttributeError:  # for example Sequential. After tf2.3.
--> 214                 key = m.name
    215             if nested:
    216                 nodes = _get_nodes(m, output_format,

AttributeError: 'ListWrapper' object has no attribute 'name'
```

Any suggestions? I am using keract version 4.3.4

**Comment by philipperemy** [comment]
@jvahl will have a look today

**Comment by philipperemy** [comment]
I'm trying to refactor the code but it will take some time.

**Comment by philipperemy** [comment]
I pushed something. Upgrade your keract lib.
It works for the timedistributed layer but does not work for the embedding layer (if you want to make it work for the embedding layer, specify the model_time and not the model). Somehow Keras is confused by your architecture and it says graph node is disconnected.

**Comment by jvahl** [comment]
Is it possible to retrieve activations of the sublayers of TimeDistributed at all? I updated to keract 4.4.0 and tried

`keract.get_activations(model, x, layer_names='lstm',nested=True)`

which gives me

`KeyError: 'Could not find a layer with name: [lstm]. Network layers are [input, timedistributed, dense]'`

**Comment by philipperemy** [comment]
@jvahl you need to specify `model_time` instead of `model` in:
```python
keract.get_activations(model, x, layer_names='lstm',nested=True)
```
It's not ideal but I'm pretty it will work.

**Comment by jvahl** [comment]
That works in the simple example but not in my application where `model` is trained and model_time doesn't exist separately.

The issue with the disconnected graph seems to be a tensorflow issue, see https://github.com/tensorflow/tensorflow/issues/42017. 

Nonetheless thanks for your help! Really appreciate the quick response.
