### ISSUE TITLE
Interaction with submodels?

### ISSUE THREAD

**Issue by LuisFMCuriel** [philipperemy/keract#149]
Hi,
First of all, very nice job! It seems like a very useful tool. I have been trying to plot a convolution layer in a submodel, but it doesn't find the layer. My model includes a subblock where I perform the convolutions in my NN. Just to be clear about what I am doing; the convolutions are inside a submodel in my main model (the shapes and number of convolution layers in the submodel image are not correct because I changed it to create the model, but is just a way to visualize the problem):
![imagen](https://user-images.githubusercontent.com/41307097/136703966-f5dd4ee7-c118-478b-9b92-5e9161714773.png)

When I try to plot the convolution layers, it does not find the layers:
```
layers= ["conv"]
activations= keract.get_activations(model, batch_test, layer_names= layers, nodes_to_evaluate= None, output_format= 'simple', auto_compile= True)

'Could not find a layer with name: [conv]. Network layers are [conv, conv_1, flatten, dense, dense_1, dense_2]'
```
I tried to go directly into the submodel by changing `model` by `model.layers[0]`

```
layers= ["conv2d"]
activations= keract.get_activations(model.layers[0], batch_test, layer_names= layers, nodes_to_evaluate= None, output_format= 'simple', auto_compile= True)

'Could not find a layer with name: [conv2d]. Network layers are [conv2d, conv2d_1, dropout]'
```

and if I just try to plot all the layers in the submodel

```
activations= keract.get_activations(model.layers[0], batch_test, layer_names= layers, nodes_to_evaluate= None, output_format= 'simple', auto_compile= True)

'Nodes list is empty. Or maybe the model is empty.'
```

which I don't think is correct because I just trained it. I would really appreciate it if you can give me some feedback to use the tool.

Thanks in advance.

**Comment by philipperemy** [comment]
@LuisFMCuriel So I've been researching extensively with the sub models and I could not find a way to make it work all the time...

**Comment by philipperemy** [comment]
So long story short, submodels are not properly handled. That's a limitation of the lib.... I'll add it to the README.

**Comment by philipperemy** [comment]
https://github.com/philipperemy/keract/blob/master/README.md#limitations--ways-of-improvement
