### ISSUE TITLE
Scikit-learn requirement

### ISSUE THREAD

**Issue by onyekaokonji** [philipperemy/keract#158]
I'd like to know if Keract now displays heatmaps with more recent versions of scikit-learn as opposed to the hard requirement of using versions <= 0.32.2. Reason i ask is, I'm trying to build a Flask backend which should display the heatmaps and so need to pip install this exact version of scikit-learn, unfortunately, subprocess.check_call keeps failing with this version specification.

**Comment by philipperemy** [comment]
@onyekaokonji I think it still needs the old version 0.32.2 or less but I can see how to upgrade it with the latest scikit-learn version.

**Comment by onyekaokonji** [comment]
That would be very appreciated @philipperemy can i ask when that might be done?

**Comment by philipperemy** [comment]
I'll try to work on it tomorrow.

**Comment by philipperemy** [comment]
So actually the work has already been done here: https://github.com/philipperemy/keract/commit/9943b6e7513b31be84ede03f72fba6853225c44e.

**Comment by philipperemy** [comment]
Pushed in version 4.5.1. This will solve your problem:

```
pip install keract --upgrade
```

**Comment by onyekaokonji** [comment]
Oh! Thank you very much! I will do the upgrade now

**Comment by onyekaokonji** [comment]
Works perfectly! Thanks again.
