### ISSUE TITLE
Get activations, activation gradients and trainable weight gradients all together

### ISSUE THREAD

**Issue by khuesmann** [philipperemy/keract#36]
Hi,

is there a way to get the activations and gradients in one go? 
Atm keract has to evaluate 3 times in order to get all the values, can it be done with one run?

Thank you!

**Comment by qwertpi** [comment]
Which functions do you want to call together?

**Comment by qwertpi** [comment]
@khuesmann do you still want this doing?

**Comment by philipperemy** [comment]
Good question. I don't see any problem to call 3 functions instead of 1. Especially because the serve different purposes.
