### ISSUE TITLE
Handle cycles in the network

### ISSUE THREAD

**Issue by pedrocolon93** [philipperemy/keract#38]
I am getting this error:

`Traceback (most recent call last):
  File "/Users/pedro/PycharmProjects/OOVconverter/visualize_drd.py", line 20, in <module>
    activations = get_activations(model, x)
  File "/Users/pedro/.conda/envs/OOVconverter/lib/python3.6/site-packages/keract/keract.py", line 77, in get_activations
    activations = _evaluate(model, layer_outputs, x, y=None)
  File "/Users/pedro/.conda/envs/OOVconverter/lib/python3.6/site-packages/keract/keract.py", line 24, in _evaluate
    return f(x_ + y_ + sample_weight_)
  File "/Users/pedro/.conda/envs/OOVconverter/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "/Users/pedro/.conda/envs/OOVconverter/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2671, in _call
    session)
  File "/Users/pedro/.conda/envs/OOVconverter/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2623, in _make_callable
    callable_fn = session._make_callable_from_options(callable_opts)
  File "/Users/pedro/.conda/envs/OOVconverter/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1471, in _make_callable_from_options
    return BaseSession._Callable(self, callable_options)
  File "/Users/pedro/.conda/envs/OOVconverter/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1425, in __init__
    session._session, options_ptr, status)
  File "/Users/pedro/.conda/envs/OOVconverter/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: retro_word_2:0 is both fed and fetched.
Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x1c3ab2ba20>>
Traceback (most recent call last):
  File "/Users/pedro/.conda/envs/OOVconverter/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1455, in __del__
    self._session._session, self._handle, status)
  File "/Users/pedro/.conda/envs/OOVconverter/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: No such callable handle: 140697188192368`

I understand that it is related to this:
[https://github.com/keras-team/keras/issues/10372](url)

But i am not sure how to add the change!

**Comment by qwertpi** [comment]
Are you sure that you are using the latest versions of Keras and Keract? get_activations works fine for me and I presume @philipperemy has tested Keract for themself as well

**Comment by andersfylling** [comment]
I have the same error. Here's my notebook: https://pastebin.com/MZyssya7

Scroll to the bottom to see the error message.

**Comment by qwertpi** [comment]
@andersfylling I can't see the error @pedrocolon93 is mentioning in the Pastebin. Are you referring to the `AttributeError: Layer sequential_5 has multiple inbound nodes, hence the notion of "layer output" is ill-defined. Use `get_output_at(node_index)` instead.`? If so could you please add a plot_model line to your code as described [here](https://keras.io/visualization/) please as that error typically occurs when there is more than one layer acting as an input to a layer hence the fact that keras gets confused as to which way to send the inputted image in via.

**Comment by andersfylling** [comment]
Hi, sorry; I must have confused myself with a previous issue I was dealing with. Anyway, here is the image: https://imgur.com/xBlffNX
![](https://i.imgur.com/xBlffNX.png)

This model is also sent through multi_gpu_model function from Keras.

I was getting the error @pedrocolon93 got when I was doing the following:
```py
outputs = [layer.get_output_at(-1) for layer in model.layers[1:]]  # skipping first layer
activation_model = models.Model(inputs=model.input, outputs=outputs)
```

Not sure if that information may help you since that was before I found this repo.

**Comment by qwertpi** [comment]
Yeah I'd drop that `outputs = [layer.get_output_at(-1) for layer in model.layers[1:]]` line if you haven't already at it's not necessary with keras.
Regarding the multiple inbound nodes error, I think it's triggered by [this line ](https://github.com/philipperemy/keract/blob/11a1128913cc69c783d2f7c5920d1d3224a03792/keract/keract.py#L73) running layer.output to return a tensor which because it's taking input from two layers causes keras to freak out. We'd need advice from @philipperemy really though as they have a much better grasp of the codebase than me due to being the one who actually wrote it and so should be able to confirm or rule out my theory and also suggest a way of fixing it

**Comment by andersfylling** [comment]
Yeah I had to switch from layer.output to layer.get_output_at as I was getting that error when I manually tried to visualize the model.. (before I found this project). So I'd agree with you fully on that one.

**Comment by philipperemy** [comment]
When the network is a DAG, it still works from one of my experiment. But it's possible that the first output is the input layer and it will crash in tensorflow. This case should already be handled: https://github.com/philipperemy/keract/blob/278b06b2ff43a1bb7659c0b05e7a1d612a7e1538/keract/keract.py#L76

```
from keras import Input, Model
from keras.layers import Dense, Concatenate
import numpy as np
import keract

#      Input
#    /      \
#   /        \
#  Dense     Dense
#   \       /
#    \     /
#     Concat


i = Input(shape=(10,), name='input')

x1 = Dense(1, name='left')(i)
x2 = Dense(1, name='right')(i)

o = Concatenate()([x1, x2])

m = Model(inputs=[i], outputs=[o])

m.compile(optimizer='adam', loss='mse')

m.summary()

inputs = np.ones(shape=(3, 10))
act = keract.get_activations(m, inputs)
```

**Comment by pedrocolon93** [comment]
For me I had to go layer by layer to visualize it.  I tried to skip through the problem layers, but it seems that keras somehow puts one of the layers as both input and output.  

I think the problem may be in the line 
` nodes = [layer.output for layer in model.layers if layer.name == layer_name or layer_name is None]
`
A few lines above the one you cited. In my case my architecture is a multitask learning one that was also a DAG. I tried to output the layers and filter them **after** the line you cited, and it seems that whatever is matched in that line doesnt work:

`    print(input_layer_outputs)
    print(layer_outputs)
    # layer_outputs = layer_outputs[2:]
`

Here is my architecture:
![DRD](https://user-images.githubusercontent.com/5157240/58257458-f4cc8800-7d3e-11e9-9da6-9c352b2706d1.png)

Let me know what you think.  Again it seems that somehow when it fetches the outputs it includes some of the inputs for reasons unbeknownst to me.

**Comment by pedrocolon93** [comment]
> Yeah I'd drop that `outputs = [layer.get_output_at(-1) for layer in model.layers[1:]]` line if you haven't already at it's not necessary with keras.
> Regarding the multiple inbound nodes error, I think it's triggered by [this line ](https://github.com/philipperemy/keract/blob/11a1128913cc69c783d2f7c5920d1d3224a03792/keract/keract.py#L73) running layer.output to return a tensor which because it's taking input from two layers causes keras to freak out. We'd need advice from @philipperemy really though as they have a much better grasp of the codebase than me due to being the one who actually wrote it and so should be able to confirm or rule out my theory and also suggest a way of fixing it

This I think is the problem, sorry I didnt read in details earlier.

**Comment by pedrocolon93** [comment]
One last thing, I modified some of the initial code to handle layers that are not 2D because my inputs are not pictures.  It should still work either way, just changed the plotting mechanism.

**Comment by philipperemy** [comment]
@pedrocolon93 thanks! Don't hesitate to submit a PR to improve the library :)

**Comment by philipperemy** [comment]
Closed due to inactivity.
