### ISSUE TITLE
Trying to apply heatmap on multi_gpu model

### ISSUE THREAD

**Issue by andersfylling** [philipperemy/keract#42]
```py
from keras.preprocessing.image import array_to_img
from PIL import Image
%matplotlib inline

x, y = gen_test.next()
image = x[1]
plt.imshow(image)
# the image is plotted successfully
```
```py
from keract import get_activations
import numpy as np

images = np.array([image])
print(images.shape)
activations = get_activations(dmodel_parallel, images, dmodel_parallel.layers[-1].name)
# prints (1, 256, 256, 3)
```
```py
from keract import display_heatmaps
display_heatmaps(activations, images)
# gives the error: activation_9_1/concat:0 (1, 2) -> Skipped. 2D Activations.
```

my model
```py
def create_model():
    m = Sequential()
    
    m.add(Conv2D(32,(3, 3), activation='relu', padding = 'same', input_shape=(None,None,3)))    
    m.add(Conv2D(32, (3, 3), activation='relu'))
    m.add(MaxPooling2D(pool_size=(2, 2)))
    m.add(Dropout(0.2))
    
    m.add(Conv2D(64,(3, 3), activation='relu', padding = 'same'))  
    m.add(Conv2D(64,(3, 3), activation='relu', padding = 'same', strides = 2))    
    m.add(MaxPooling2D(pool_size=(2, 2)))
    m.add(Dropout(0.5))
    
    m.add(Conv2D(64,(3, 3), activation='relu', padding = 'same'))    
    m.add(Conv2D(64,(3, 3), activation='relu', padding = 'same'))
    m.add(Conv2D(64,(3, 3), activation='relu', padding = 'same', strides = 2))    
    m.add(MaxPooling2D(pool_size=(2, 2)))
    m.add(Dropout(0.5))    
    
    m.add(Conv2D(64,(3, 3), padding = 'same'))
    m.add(Activation('relu'))
    m.add(Conv2D(64,(1, 1),padding='valid'))
    m.add(Activation('relu'))
    m.add(Conv2D(2, (1, 1), padding='valid'))

    m.add(GlobalAveragePooling2D())
    return m

model = create_model()
model.add(Activation('softmax'))

model = multi_gpu_model(model, gpus=[0,1])
model.compile(optimizer="adam",
    loss="categorical_crossentropy", 
    metrics=["accuracy"])
```

Here's the shape of the activations: 
`array([[0.9661835 , 0.03381654]], dtype=float32)`

**Comment by qwertpi** [comment]
If you are just getting some 2D activations that isn't an error, it just means those activations aren't images  (normally happens with dense layers etc. in CNNs as the neurons in those layers don't output images) so they aren't shown by keract. If all no acitvations are beeing shown beacuse of this then that is an issue

**Comment by andersfylling** [comment]
Ah that makes sense. If I try to use the entire compiled model:
```py
activations = get_activations(dmodel_parallel, images)
```

I get the error
`Layer sequential_2 has multiple inbound nodes, hence the notion of "layer output" is ill-defined. Use `get_output_at(node_index)` instead.`

**Comment by qwertpi** [comment]
Yeah, keract and pretty much all keras visualisation code doesn't place nicely with models within models. If you only want to visualise the submodel I'd use get_activations(dmodel_parallel.layers[3]) that way it will only see the submodel and so should work.

**Comment by qwertpi** [comment]
Yeah, keract and pretty much all keras visualisation code doesn't play nicely with models within models. If you only want to visualise the submodel I'd use get_activations(dmodel_parallel.layers[3]) that way it will only see the submodel and so should work.

**Comment by qwertpi** [comment]
@andersfylling Did you ever get this to work?
