### ISSUE TITLE
AttributeError: 'Model' object has no attribute '_is_compiled'

### ISSUE THREAD

**Issue by sudonto** [philipperemy/keract#43]
Hi @philipperemy , when I run example/vgg16.py, that error shows. Could you tell me how to solve this problem?
I am using Python3.5, Tensorflow 1.11.0, Keras 2.1.6. Thank you.

**Comment by philipperemy** [comment]
Hum seems like you're using an old version of Keras @sudonto

**Comment by sudonto** [comment]
OK, upgraded Keras to 2.2.3 and it works. Thanks.

**Comment by philipperemy** [comment]
Ok I'm going to add that in the requirements.txt :)
