### ISSUE TITLE
Error: TypeError: Invalid dimensions for image data

### ISSUE THREAD

**Issue by sudonto** [philipperemy/keract#44]
Hi @philipperemy , I am trying to visualize my activations but this error showed up:
`slow_conv1/add:0 (1, 2, 112, 112, 64)
Traceback (most recent call last):
  File "vis.py", line 107, in <module>
    keract.display_activations(activations)
  File "C:\Users\xxx\Envs\krtf\lib\site-packages\keract\keract.py", line 111, in display_activations
    hmap = axes.flat[i].imshow(img, cmap=cmap)
  File "C:\Users\xxx\Envs\krtf\lib\site-packages\matplotlib\__init__.py", line 1810, in inner
    return func(ax, *args, **kwargs)
  File "C:\Users\xxx\Envs\krtf\lib\site-packages\matplotlib\axes\_axes.py", line 5494, in imshow
    im.set_data(X)
  File "C:\Users\xxx\Envs\krtf\lib\site-packages\matplotlib\image.py", line 638, in set_data
    raise TypeError("Invalid dimensions for image data")
TypeError: Invalid dimensions for image data`

I am working with 3D conv, is it compatible with your lib? Thanks (again)!

**Comment by qwertpi** [comment]
I'm guessing 3D convs won't work in terms of displaying but will be retrieved by keract fine. As you can see when running display_activations keract uses matplotlib which correctly complains that it can't show 3D images (think about it, how do you expect to see these 3D images on your 2D monitor anyway?)

**Comment by sudonto** [comment]
Well, I'm expecting Keract to handle "the stacked images" internally, splitting and feeding it to matplotlib.

**Comment by qwertpi** [comment]
> Well, I'm expecting Keract to handle "the stacked images" internally, splitting and feeding it to matplotlib.

That's beyond what Keras currently does but it could be made to do so with some numpy.reshape()'s

**Comment by philipperemy** [comment]
@sudonto any PR is welcome :)
