### ISSUE TITLE
OOM when trying to get activations for large image

### ISSUE THREAD

**Issue by bjtho08** [philipperemy/keract#47]
I realize this is a memory issue, but I was wondering if you have any ideas as to how I can circumvent the issue. When I run predictions on large images I cut them into smaller tiles and reassemble them afterwards, but I have trouble seeing how to properly do that with the data structure delivered by `keract.get_activations()`.

**Comment by qwertpi** [comment]
[Here](https://github.com/philipperemy/keract/blob/6471feb95a984ff195991e9c74b9597b34863a15/keract/keract.py#L71) it is mentioned that get_activations returns a dictionary with the keys as the layer names and the values as the activations. [This thread](https://stackoverflow.com/questions/1781571/how-to-concatenate-two-dictionaries-to-create-a-new-one-in-python) suggests that dict_1.update(dict_2) should allow you to concatenate dictionaries. However, I must say if you get OOM when doing normal predictions I suspect you'll struggle to store all of the activations in memory at once.

**Comment by bjtho08** [comment]
@qwertpi thanks for the suggestions, I'll have to check that out. I only get OOM because I am running a rather wide net on a GPU. I have 126 GiB RAM installed on the machine, but only a single 1080 TI with 11 GiB VRAM. I guess, if I could switch the model from GPU to CPU when predicting, then it would fix the OOM issue entirely. Do you know if that is easily manageable?

**Comment by qwertpi** [comment]
> @qwertpi thanks for the suggestions, I'll have to check that out. I only get OOM because I am running a rather wide net on a GPU. I have 126 GiB RAM installed on the machine, but only a single 1080 TI with 11 GiB VRAM. I guess, if I could switch the model from GPU to CPU when predicting, then it would fix the OOM issue entirely. Do you know if that is easily manageable?

I've never done it myself but I've heard you can use 
```
with tf.device('/cpu:0'):
    #some code here
to force keras to use the CPU https://blog.keras.io/keras-as-a-simplified-interface-to-tensorflow-tutorial.html
```

**Comment by philipperemy** [comment]
@bjtho08 A simple command like this should force the execution on the CPU:

```
export CUDA_VISIBLE_DEVICES=; python my_script.py
```

**Comment by philipperemy** [comment]
The second way to do it is to run one image at a time. Your GPU memory should be sufficient to do that.

**Comment by philipperemy** [comment]
Feel free to re-open it if you still encounter the problem.
