### ISSUE TITLE
Why are all the layers skipped? 

### ISSUE THREAD

**Issue by marangiop** [philipperemy/keract#48]
I followed one of the examples on the repoistory. Here is the keract code I am using and below you can see the error. Why are the layers being skipped? Do I need to change the number of filters to 1 for all my convolutions? How does that make sense?

import keract
activations = keract.get_activations(model, x_training)
first = activations.get('conv2d_1/Relu:0')
keract.display_activations(activations, save=True)

OUTPUT
input_1:0 (256, 256, 1) -> Skipped. First dimension is not 1.
conv2d_1/Relu:0 (89, 256, 256, 64) -> Skipped. First dimension is not 1.
conv2d_2/Relu:0 (89, 256, 256, 64) -> Skipped. First dimension is not 1.
max_pooling2d_1/MaxPool:0 (89, 128, 128, 64) -> Skipped. First dimension is not 1.
conv2d_3/Relu:0 (89, 128, 128, 128) -> Skipped. First dimension is not 1.
conv2d_4/Relu:0 (89, 128, 128, 128) -> Skipped. First dimension is not 1.
max_pooling2d_2/MaxPool:0 (89, 64, 64, 128) -> Skipped. First dimension is not 1.
conv2d_5/Relu:0 (89, 64, 64, 256) -> Skipped. First dimension is not 1.
conv2d_6/Relu:0 (89, 64, 64, 256) -> Skipped. First dimension is not 1.
max_pooling2d_3/MaxPool:0 (89, 32, 32, 256) -> Skipped. First dimension is not 1.
conv2d_7/Relu:0 (89, 32, 32, 512) -> Skipped. First dimension is not 1.
conv2d_8/Relu:0 (89, 32, 32, 512) -> Skipped. First dimension is not 1.
dropout_1/cond/Merge:0 (89, 32, 32, 512) -> Skipped. First dimension is not 1.
max_pooling2d_4/MaxPool:0 (89, 16, 16, 512) -> Skipped. First dimension is not 1.
conv2d_9/Relu:0 (89, 16, 16, 1024) -> Skipped. First dimension is not 1.
conv2d_10/Relu:0 (89, 16, 16, 1024) -> Skipped. First dimension is not 1.
dropout_2/cond/Merge:0 (89, 16, 16, 1024) -> Skipped. First dimension is not 1.
up_sampling2d_1/ResizeNearestNeighbor:0 (89, 32, 32, 1024) -> Skipped. First dimension is not 1.
conv2d_11/Relu:0 (89, 32, 32, 512) -> Skipped. First dimension is not 1.
concatenate_1/concat:0 (89, 32, 32, 1024) -> Skipped. First dimension is not 1.
conv2d_12/Relu:0 (89, 32, 32, 512) -> Skipped. First dimension is not 1.
conv2d_13/Relu:0 (89, 32, 32, 512) -> Skipped. First dimension is not 1.
up_sampling2d_2/ResizeNearestNeighbor:0 (89, 64, 64, 512) -> Skipped. First dimension is not 1.
conv2d_14/Relu:0 (89, 64, 64, 256) -> Skipped. First dimension is not 1.
concatenate_2/concat:0 (89, 64, 64, 512) -> Skipped. First dimension is not 1.
conv2d_15/Relu:0 (89, 64, 64, 256) -> Skipped. First dimension is not 1.
conv2d_16/Relu:0 (89, 64, 64, 256) -> Skipped. First dimension is not 1.
up_sampling2d_3/ResizeNearestNeighbor:0 (89, 128, 128, 256) -> Skipped. First dimension is not 1.
conv2d_17/Relu:0 (89, 128, 128, 128) -> Skipped. First dimension is not 1.
concatenate_3/concat:0 (89, 128, 128, 256) -> Skipped. First dimension is not 1.
conv2d_18/Relu:0 (89, 128, 128, 128) -> Skipped. First dimension is not 1.
conv2d_19/Relu:0 (89, 128, 128, 128) -> Skipped. First dimension is not 1.
up_sampling2d_4/ResizeNearestNeighbor:0 (89, 256, 256, 128) -> Skipped. First dimension is not 1.
conv2d_20/Relu:0 (89, 256, 256, 64) -> Skipped. First dimension is not 1.
concatenate_4/concat:0 (89, 256, 256, 128) -> Skipped. First dimension is not 1.
conv2d_21/Relu:0 (89, 256, 256, 64) -> Skipped. First dimension is not 1.
conv2d_22/Relu:0 (89, 256, 256, 64) -> Skipped. First dimension is not 1.
conv2d_23/Relu:0 (89, 256, 256, 2) -> Skipped. First dimension is not 1.
conv2d_24/Sigmoid:0 (89, 256, 256, 1) -> Skipped. First dimension is not 1.

**Comment by qwertpi** [comment]
My guess is you've inputted 89 images instead of just the 1

**Comment by philipperemy** [comment]
@marangiop use only one image. You're going to have a hard time if you want to visualise all the layers with 89 images at the same time.
