### ISSUE TITLE
_standardize_user_data may return None for sample_weights

### ISSUE THREAD

**Issue by pedro-r-marques** [philipperemy/keract#50]
The tensorflow branch the keras engine was modified such that model._standardize_user_data will now return None instead of an empty list when sample_weights are not defined.

Although the code states:
```
    Returns:
      A tuple of 3: inputs (arrays or dicts, depending on whether `x` was a dict
      or not), target arrays, sample-weight arrays.
      If the model's input and targets are symbolic, these lists are empty
      (since the model takes no user-provided data, instead the data comes
      from the symbolic inputs/targets).
```

The following commit seems to have changed the default sample weights return from [] to None.

https://github.com/tensorflow/tensorflow/commit/41abdd1212777a60e0d97ada4a39d13f2b9014a1

This in turn causes the list add operation in the following return statement to fail:
```
def _evaluate(model: Model, nodes_to_evaluate, x, y=None):
   [...]
    x_, y_, sample_weight_ = model._standardize_user_data(x, y)
    return f(x_ + y_ + sample_weight_)
```

**Comment by philipperemy** [comment]
Thanks for reporting @pedro-r-marques do you have any ideas to fix that?

**Comment by pedro-r-marques** [comment]
The following check after the call to ```_standardize_user_data``` fixes it for me.

```
    x_, y_, sample_weight_ = model._standardize_user_data(x, y)
    if sample_weight_ is None:
      sample_weight_ = []
```

Apologies but I've not had time recently to submit a pull request.

**Comment by philipperemy** [comment]
@pedro-r-marques no problem. What you're doing already helps a lot :)

**Comment by philipperemy** [comment]
Fixed in https://github.com/philipperemy/keract/pull/65.
I used a try catch but your solution also works.
