### ISSUE TITLE
What does the numbered bar on the right mean?

### ISSUE THREAD

**Issue by marangiop** [philipperemy/keract#52]
Hello, I have been able to run keract without problems on my CNN, but I am just wondering what does the numbered bar going from 0.2 to 0.8 mean? 
<img width="325" alt="right_bar_keract" src="https://user-images.githubusercontent.com/29339953/61598570-e94eed80-ac17-11e9-89ec-631dcf19b63e.PNG">

**Comment by qwertpi** [comment]
It's a key telling you that activations at 0.2 are that dark purple colour (the activations for that layer don't go far below 0.2), activations at 1.0 are that bluey-green colour, 1.4 are that greeny colour, 1.6 are that yellowy greeny colour with ones slightly above 1.6 (the activations for that layer don't go far above 1.6) being yellow. 
You might also be interested to know that if you're running a recent enough version of keract (anything above 2.5.3 (the latest release [has a bug](https://github.com/philipperemy/keract/pull/51) in it so I would recommend installing 2.5.4)), you can change the colour the activations are displayed in (and therefore the colours of the key) to give activations in grayscale (called gray by matplotlib) or any other valid [matplotlib colour map](https://matplotlib.org/tutorials/colors/colormaps.html) through the optional cmap parameter for display_activations

**Comment by marangiop** [comment]
@qwertpi Thank you for your reply. 

It is clear now that the numbers on the legend indicate activation. But my questions is: why such values? Is this dependent on the type of activation function (e.g. ReLu) used? Also, why do you have variation in the actual numbers of the scale across different conv layers (e.g. sometimes the maximum is 2.0, sometimes 3.5, sometimes 0.1)?

Is this an absolute scale, in the sense that an activation of 1.6 with ReLu on the first convolution, regardless of the architecture, is generally considered to be good/strong activation and 0.4, for example, a low one?

Or is it relative, in the sense that it is computed mostly based on the kind of input presented at each layer? 

I have the feeling that it's the second one, but it would be great if you could maybe provide some rationale as to why this is case

**Comment by qwertpi** [comment]
> @qwertpi Thank you for your reply.
> 
> It is clear now that the numbers on the legend indicate activation. But my questions is: why such values? Is this dependent on the type of activation function (e.g. ReLu) used? Also, why do you have variation in the actual numbers of the scale across different conv layers (e.g. sometimes the maximum is 2.0, sometimes 3.5, sometimes 0.1)?
> 
> Is this an absolute scale, in the sense that an activation of 1.6 with ReLu on the first convolution, regardless of the architecture, is generally considered to be good/strong activation and 0.4, for example, a low one?
> 
> Or is it relative, in the sense that it is computed mostly based on the kind of input presented at each layer?
> 
> I have the feeling that it's the second one, but it would be great if you could maybe provide some rationale as to why this is case

The term activation can be somewhat confusing as it has strong connotations with activation functions, in reality, all that get_activations does is allow you to peer inside your model by getting the *output* of your model at a particular layer when the network is given a particular input. 
This output is however obviously affected by the activation function, in this case, you can see that as the layer you are looking at is a ReLU it obviously has no negative values.
This variance is simply the variance in the output of your model at each layer.
You are correct in thinking it is the second one, the colours are dynamically assigned based on the layer's output so the meaning of a colour differs from one layer to the next (it will represent a different number  but still represent the same relative value of that number overall eg. minimum, maximum, middle, just above minimum etc.)

**Comment by philipperemy** [comment]
I'll close this issue @marangiop feel free to re-open it should not it be clear enough. Thanks
