### ISSUE TITLE
Is there any way of reversing an activation map from Keract or set values of classes?

### ISSUE THREAD

**Issue by marangiop** [philipperemy/keract#54]
<img width="600" alt="sigmoid_activation_output_compared_with_predicted" src="https://user-images.githubusercontent.com/29339953/62988255-9560ae80-be3b-11e9-88d0-949b3cae99a9.PNG">

I am working with the U-net neural network for image segmentation (i.e. binary classification at every pixel). I feed a test image (top), then I get a prediction out by the network (bottom left) and then I used the keract display_activations function on the last convolution of the network with sigmoid activation (borrom right), I get an activation map, with yellow colour for a value of 1 assigned for white pixel and blue colour for a value of 0 assigned for black pixels. If I am interested in having my black pixels to be classified as being in class 1 (therefore yellow colour), is there any way to set this in Keract as to change the current behaviour? I am not sure if this is  Keract specific question, but did not find solutions elsewhere. Any advice would be appreciated.

**Comment by qwertpi** [comment]
I have to say this is a somewhat unconventional way of visualising U net segmentation maps but it sounds like you need a different [matplotlib colour map](https://matplotlib.org/tutorials/colors/colormaps.html), you can change the colour map through the `cmap` argument for `display_activations`

**Comment by philipperemy** [comment]
@marangiop what do you want exactly? changing the color from yellow to black? Having a threshold to color all the points greater than 0.5 to black and the rest to white?

**Comment by philipperemy** [comment]
Closed due to inactivity.
