### ISSUE TITLE
Using keract with flow_from_directory() and datagenerators?

### ISSUE THREAD

**Issue by BraveDistribution** [philipperemy/keract#55]
Is there a way to use keract with flow from directory and datagenerators?

def plot_images_from_layers(model_path):
    model = load_model(model_path)
    activations = get_activations(model, x, "fc1")

I have a trained model, I would like to see what "fully connected layers" and "convolutional layers" see. I don't have "x" input array, but I use generators/flow_from directory functions. Is there a way how to use keract?

**Comment by qwertpi** [comment]
> Is there a way to use keract with flow from directory and datagenerators?
> 
> def plot_images_from_layers(model_path):
> model = load_model(model_path)
> activations = get_activations(model, x, "fc1")
> 
> I have a trained model, I would like to see what "fully connected layers" and "convolutional layers" see. I don't have "x" input array, but I use generators/flow_from directory functions. Is there a way how to use keract?

Typically you only want to input one image at a time to Keract meaning it's probably easier for everyone involved if you just load one from disk.

**Comment by BraveDistribution** [comment]
Thanks, will try!
