### ISSUE TITLE
TypeError: can only concatenate list (not "NoneType") to list

### ISSUE THREAD

**Issue by starkgate** [philipperemy/keract#59]
I'm getting the following error when trying to use the example you gave for keract:
```
Traceback (most recent call last):
  File "new.py", line 139, in <module>
    activations = get_activations(model, test_volumes_mri)
  File ".../.local/lib/python3.7/site-packages/keract/keract.py", line 80, in get_activations
    activations = _evaluate(model, layer_outputs, x, y=None)
  File ".../.local/lib/python3.7/site-packages/keract/keract.py", line 27, in _evaluate
    return f(x_ + y_ + sample_weight_)
TypeError: can only concatenate list (not "NoneType") to list
```

The code (just the part that crashes. The model itself compiles, trains and evaluates just fine):
```
from keract import get_activations,display_activations,display_heatmaps,get_gradients_of_trainable_weights,get_gradients_of_activations
activations = get_activations(model, test_volumes_mri)
display_activations(activations, cmap="gray", save=True)
display_heatmaps(activations, input_image, save=True)
get_gradients_of_trainable_weights(model, test_volumes_mri, images_groundtruth)
get_gradients_of_activations(model, test_volumes_mri, images_groundtruth)
```

**Comment by qwertpi** [comment]
What's your model architecture and what is the shape of test_volumes_mri? Also, are keras, keract, TensorFlow etc. up to date on your system?

**Comment by CreeperLava** [comment]
I'm using the new TF 2.0 RC1 release. test_volumes_mri is a 4 dimensional tensor, with an empty 4th dimension (eg 250x250x250x1). Model architecture is essentially Conv2D alternating with BatchNormalization to get from 250x250x250 to 250x250x1.

**Comment by qwertpi** [comment]
> I'm using the new TF 2.0 RC1 release. test_volumes_mri is a 4 dimensional tensor, with an empty 4th dimension (eg 250x250x250x1). Model architecture is essentially Conv2D alternating with BatchNormalization to get from 250x250x250 to 250x250x1.

It might be that TF 2.0 is messing with keract, we have already had a report (#58) of tf.keras in TF 2.0 not playing nicely with keract

**Comment by CreeperLava** [comment]
That's my assumption too. It's a shame, I really wanted to see what keract had to offer

**Comment by FlorinAndrei** [comment]
Same issue with TF 1.14

This is the model:

https://github.com/FlorinAndrei/TensorAim/blob/keract_issue/old/model.py

This is the training script:

https://github.com/FlorinAndrei/TensorAim/blob/keract_issue/old/train_real_world_model.py

I tried to do get_activations() / display_activations() in this script:

https://github.com/FlorinAndrei/TensorAim/blob/keract_issue/old/camera_live_test.py

**Comment by philipperemy** [comment]
@starkgate @FlorinAndrei work to support newest versions of Tensorflow 1.14 and 2.0 will start soon :)

**Comment by philipperemy** [comment]
@FlorinAndrei can you extract the simplest snippet where the call to keract failed?

**Comment by philipperemy** [comment]
Fixed in https://github.com/philipperemy/keract/pull/65
