### ISSUE TITLE
IndexError with multiple inputs

### ISSUE THREAD

**Issue by illith** [philipperemy/keract#67]
Thank you for your work! display_activations is work ,but i got the following error with display_heatmaps():
```
Traceback (most recent call last):
  File "/home/sipl-dl/.vscode/extensions/ms-python.python-2019.10.41019/pythonFiles/ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "/home/sipl-dl/.vscode/extensions/ms-python.python-2019.10.41019/pythonFiles/lib/python/old_ptvsd/ptvsd/__main__.py", line 432, in main
    run()
  File "/home/sipl-dl/.vscode/extensions/ms-python.python-2019.10.41019/pythonFiles/lib/python/old_ptvsd/ptvsd/__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "/home/sipl-dl/anaconda3/envs/keras/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/home/sipl-dl/anaconda3/envs/keras/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/sipl-dl/anaconda3/envs/keras/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/sipl-dl/code/streamer/attention_map_CAM3.py", line 100, in <module>
    main()
  File "/home/sipl-dl/code/streamer/attention_map_CAM3.py", line 97, in main
    validate(image_shape=image_shape, class_limit=None)
  File "/home/sipl-dl/code/streamer/attention_map_CAM3.py", line 89, in validate
    display_heatmaps(activations, imgx, save=False)
  File "/home/sipl-dl/anaconda3/envs/keras/lib/python3.6/site-p
```ackages/keract/keract.py", line 226, in display_heatmaps
    img = acts[0, :, :, i]
IndexError: too many indices for array
```

and my code is :
```
    model = load_model('multi3_cgru_0527 22:39 69.83.h5',custom_objects={'categorical_focal_loss_fixed':categorical_focal_loss_fixed})
    model.summary()
    img_path1 = 'data/attention/video/v1 - 48of99-0001.png'
    img_path2= 'data/attention/audio/v1-48of99chunk0.png'
    img_path3='data/attention/flow/frame_00001.png'

    img1 = image.load_img(img_path1, target_size=(299, 299)) 
    img2 = image.load_img(img_path2, target_size=(299, 299)) 
    img3 = image.load_img(img_path3, target_size=(299, 299)) 
    x1= image.img_to_array(img1) 
    x2= image.img_to_array(img2) 
    x3 = image.img_to_array(img3) 
    x1 = np.expand_dims(x1, axis=0)
    x2 = np.expand_dims(x2, axis=0) 
    x3 = np.expand_dims(x3, axis=0)  
    x=[x1,x2,x3]


    activations = get_activations(model, x, layer_name='concatenate_3')
    print(activations)
    imgx = image.load_img(img_path1)
    imgx = np.array(imgx)
    imgx = np.expand_dims(imgx, axis=0) 
    display_heatmaps(activations, imgx, save=False)
```

Thank you!

**Comment by illith** [comment]
ant

**Comment by qwertpi** [comment]
I wrote the heatmap code! Having had a flick through the current source code it seem to me that the heatmap code has less support for various image formats than get activatons. Is your image grayscale by any chance?

**Comment by illith** [comment]
> I wrote the heatmap code! Having had a flick through the current source code it seems to me that the heatmap code has less support for various image formats than get_activations (sorry about that). Is your image grayscale by any chance?
Thanks for your work.  the heatmap code is good ,the error may beacouse my multiple inputs.  The img1 is color image（video frame），img2 is optical flow color image， img3 is spectrum image（color image）。

**Comment by qwertpi** [comment]
> @qwertpi
> Thanks for your work. the heatmap code is good ,the error may beacouse my multiple inputs. The img1 is color image（video frame），img2 is optical flow color image， img3 is spectrum image（color image）。

Are they channels first or channels last?

**Comment by illith** [comment]
@qwertpi      "image_data_format": "channels_last"

**Comment by qwertpi** [comment]
> @qwertpi "image_data_format": "channels_last"

That should work fine with display_activations, what's the output of `imgx.shape()`?

**Comment by illith** [comment]
@qwertpi yes! display_activations is work fine.
when  np.array(imgx)->(240,320,3)
 and then np.expand_dims(imgx,axis=0)->(1,240,320,3)

**Comment by qwertpi** [comment]
> @qwertpi yes! display_activations is work fine.
> when np.array(imgx)->(240,320,3)
> and then np.expand_dims(imgx,axis=0)->(1,240,320,3)

Sorry I meant display_heatmaps. Your imgx seems fine, what's the output of `activations.shape()`

**Comment by illith** [comment]
@qwertpi     print(activations.shape):
AttributeError: 'collections.OrderedDict' object has no attribute 'shape'

**Comment by qwertpi** [comment]
> @qwertpi print(activations.shape):
> AttributeError: 'collections.OrderedDict' object has no attribute 'shape'

Sorry my mistake run `print([len(a) for a in activations.values()])`

**Comment by illith** [comment]
@qwertpi         [(1, 10, 200)]

**Comment by qwertpi** [comment]
> @qwertpi [(1, 10, 200)]

That'll be the problem, for that layer the code needs to be doing `img = acts[0, :, i]`, I'll put together a pull request now

**Comment by illith** [comment]
i have change the sorce code
`for i in range(nrows * ncols):
            if i < acts.shape[-1]:
               # print(acts.shape)
                img = acts[0, :, i]`
but i meet a new error```
`2019-10-24 16:45:45.272836: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library libcublas.so.10.0 locally
[(1, 10, 200)]
concatenate_3/concat:0 (1, 10, 200) 
Traceback (most recent call last):
  File "/home/sipl-dl/.vscode/extensions/ms-python.python-2019.10.41019/pythonFiles/ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "/home/sipl-dl/.vscode/extensions/ms-python.python-2019.10.41019/pythonFiles/lib/python/old_ptvsd/ptvsd/__main__.py", line 432, in main
    run()
  File "/home/sipl-dl/.vscode/extensions/ms-python.python-2019.10.41019/pythonFiles/lib/python/old_ptvsd/ptvsd/__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "/home/sipl-dl/anaconda3/envs/keras/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/home/sipl-dl/anaconda3/envs/keras/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/sipl-dl/anaconda3/envs/keras/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/sipl-dl/code/streamer/attention_map_keract.py", line 103, in <module>
    main()
  File "/home/sipl-dl/code/streamer/attention_map_keract.py", line 100, in main
    validate(image_shape=image_shape, class_limit=None)
  File "/home/sipl-dl/code/streamer/attention_map_keract.py", line 92, in validate
    display_heatmaps(activations, imgx, save=False)
  File "/home/sipl-dl/anaconda3/envs/keras/lib/python3.6/site-packages/keract/keract.py", line 229, in display_heatmaps
    img = scaler.transform(img)
  File "/home/sipl-dl/anaconda3/envs/keras/lib/python3.6/site-packages/sklearn/preprocessing/data.py", line 396, in transform
    force_all_finite="allow-nan")
  File "/home/sipl-dl/anaconda3/envs/keras/lib/python3.6/site-packages/sklearn/utils/validation.py", line 552, in check_array
    "if it contains a single sample.".format(array))
ValueError: Expected 2D array, got 1D array instead:
array=[0.47444132 0.5048855  0.33221674 0.10920312 0.02226315 0.32085362
 0.37543452 0.44242328 0.6692577  0.5671499 ].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.`
Is there anything else that needs to be changed?

**Comment by illith** [comment]
@qwertpi  in that code ``i meet this :
`  File "/home/sipl-dl/anaconda3/envs/keras/lib/python3.6/site-packages/keract/keract.py", line 233, in display_heatmaps
    if data_format == 'channels_last':
NameError: name 'data_format' is not defined`
and then i add `data_format='channels_last'`
but i  meet

`File "/home/sipl-dl/code/streamer/attention_map_keract.py", line 92, in validate
    display_heatmaps(activations, imgx, save=False)
  File "/home/sipl-dl/anaconda3/envs/keras/lib/python3.6/site-packages/keract/keract.py", line 251, in display_heatmaps
    img = Image.fromarray(img)
  File "/home/sipl-dl/anaconda3/envs/keras/lib/python3.6/site-packages/PIL/Image.py", line 2547, in fromarray
    size = shape[1], shape[0]
IndexError: tuple index out of range`

**Comment by philipperemy** [comment]
Pushed to 2.8.4! Thanks :)

**Comment by illith** [comment]
Most of the activation maps I've seen are irregular shapes like the example in project profile, but this one is linear,I haven't seen before.··
output of  display_activations :
``
![Figure_123](https://user-images.githubusercontent.com/10329923/67564250-2f56a880-f755-11e9-879b-4c3e294fcdaa.png)

**Comment by qwertpi** [comment]
> Most of the activation maps I've seen are irregular shapes like the example in project profile, but this one is linear,I haven't seen before.··
> output of display_activations :
> ``
> ![Figure_123](https://user-images.githubusercontent.com/10329923/67564250-2f56a880-f755-11e9-879b-4c3e294fcdaa.png)
If you look at the output of display_activations you should be able to see that that output of each neuron is 1D not 2D hence why some of the heatmaps might look a bit weird as that 1D activation has to be extrapolated to cover an entire 2D image in a heatmap

**Comment by illith** [comment]
@qwertpi Thank uuuuuuuuu! Your answer makes me understand! I have another question, what is the reason for the output to be 1D? My network is xception, then reshape and send it to Gru. Is it right?

**Comment by qwertpi** [comment]
> @qwertpi Thank uuuuuuuuu! Your answer makes me understand! I have another question, what is the reason for the output to be 1D? My network is xception, then reshape and send it to Gru. Is it right?

It's probably just that layer, could you run
```
from keras.utils import plot_model
plot_model(model, to_file='model.png', show_shapes=True, expand_nested=True)
```
and upload model.png then we'll be able to get a sense for the output shape of all the layers in the model

**Comment by illith** [comment]
@qwertpi Thank you for taking the time to help me! My network is ：
![model](https://user-images.githubusercontent.com/10329923/67567262-2cab8180-f75c-11e9-85aa-cdc46a400183.png)

**Comment by qwertpi** [comment]
It looks to me like for heatmaps you'd want a layer from the xception submodel as that has convolutional layers that will produce image like output whereas the time distributed layers not long after the end of the xception model lose that 2 dimensionality ready for input to the dense layer

**Comment by illith** [comment]
@qwertpi  thank you！Deep learning is so much, and I know so little······hhhhhh Thank you for helping me so much。I'm trying to delete the time distributed layer.

**Comment by qwertpi** [comment]
> @qwertpi thank you！Deep learning is so much, and I know so little······hhhhhh Thank you for helping me so much。I'm trying to delete the time distributed layer.

What do you mean by "I'm trying to delete the time distributed layer."?

**Comment by illith** [comment]
@qwertpi  I‘m trying to produce the right heatmaps  and changing the code to avoid 1D output.  I had changed the time distributed layer but failed。。。

**Comment by qwertpi** [comment]
I'd advise against removing the time distributed layers as they will be helping your model to make good predictions. Instead, get the output at block14_sepconv2_act or any other xception layer as they will still be impacting on the final prediction and will give a 2D output

**Comment by illith** [comment]
@qwertpi when i use model.summary。 output as follows:
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
image (InputLayer)              (None, 299, 299, 3)  0                                            
__________________________________________________________________________________________________
audio (InputLayer)              (None, 299, 299, 3)  0                                            
__________________________________________________________________________________________________
flow (InputLayer)               (None, 299, 299, 3)  0                                            
__________________________________________________________________________________________________
xception (Model)                multiple             20861480    image[0][0]                      
                                                                 audio[0][0]                      
                                                                 flow[0][0]                       
__________________________________________________________________________________________________
reshape_1 (Reshape)             (None, 10, 20480)    0           xception[1][0]                   
__________________________________________________________________________________________________
reshape_2 (Reshape)             (None, 10, 20480)    0           xception[2][0]                   
__________________________________________________________________________________________________
reshape_3 (Reshape)             (None, 10, 20480)    0           xception[3][0]                   
__________________________________________________________________________________________________
bidirectional_1 (Bidirectional) (None, 10, 4096)     276836352   reshape_1[0][0]                  
__________________________________________________________________________________________________
bidirectional_2 (Bidirectional) (None, 10, 4096)     276836352   reshape_2[0][0]                  
__________________________________________________________________________________________________
bidirectional_3 (Bidirectional) (None, 10, 4096)     276836352   reshape_3[0][0]                  
__________________________________________________________________________________________________
time_distributed_1 (TimeDistrib (None, 10, 100)      409700      bidirectional_1[0][0]            
__________________________________________________________________________________________________
time_distributed_2 (TimeDistrib (None, 10, 100)      409700      bidirectional_2[0][0]            
__________________________________________________________________________________________________
time_distributed_3 (TimeDistrib (None, 10, 100)      409700      bidirectional_3[0][0]            
__________________________________________________________________________________________________
dot_1 (Dot)                     (None, 10, 10)       0           time_distributed_1[0][0]         
                                                                 time_distributed_2[0][0]         
__________________________________________________________________________________________________
dot_4 (Dot)                     (None, 10, 10)       0           time_distributed_2[0][0]         
                                                                 time_distributed_3[0][0]         
__________________________________________________________________________________________________
dot_7 (Dot)                     (None, 10, 10)       0           time_distributed_3[0][0]         
                                                                 time_distributed_1[0][0]         
__________________________________________________________________________________________________
activation_1 (Activation)       (None, 10, 10)       0           dot_1[0][0]                      
__________________________________________________________________________________________________
activation_2 (Activation)       (None, 10, 10)       0           dot_4[0][0]                      
__________________________________________________________________________________________________
activation_3 (Activation)       (None, 10, 10)       0           dot_7[0][0]                      
__________________________________________________________________________________________________
dot_2 (Dot)                     (None, 10, 100)      0           activation_1[0][0]               
                                                                 time_distributed_2[0][0]         
__________________________________________________________________________________________________
dot_3 (Dot)                     (None, 10, 100)      0           activation_1[0][0]               
                                                                 time_distributed_1[0][0]         
__________________________________________________________________________________________________
dot_5 (Dot)                     (None, 10, 100)      0           activation_2[0][0]               
                                                                 time_distributed_3[0][0]         
__________________________________________________________________________________________________
dot_6 (Dot)                     (None, 10, 100)      0           activation_2[0][0]               
                                                                 time_distributed_2[0][0]         
__________________________________________________________________________________________________
dot_8 (Dot)                     (None, 10, 100)      0           activation_3[0][0]               
                                                                 time_distributed_1[0][0]         
__________________________________________________________________________________________________
dot_9 (Dot)                     (None, 10, 100)      0           activation_3[0][0]               
                                                                 time_distributed_3[0][0]         
__________________________________________________________________________________________________
multiply_1 (Multiply)           (None, 10, 100)      0           dot_2[0][0]                      
                                                                 time_distributed_1[0][0]         
__________________________________________________________________________________________________
multiply_2 (Multiply)           (None, 10, 100)      0           dot_3[0][0]                      
                                                                 time_distributed_2[0][0]         
__________________________________________________________________________________________________
multiply_3 (Multiply)           (None, 10, 100)      0           dot_5[0][0]                      
                                                                 time_distributed_2[0][0]         
__________________________________________________________________________________________________
multiply_4 (Multiply)           (None, 10, 100)      0           dot_6[0][0]                      
                                                                 time_distributed_3[0][0]         
__________________________________________________________________________________________________
multiply_5 (Multiply)           (None, 10, 100)      0           dot_8[0][0]                      
                                                                 time_distributed_3[0][0]         
__________________________________________________________________________________________________
multiply_6 (Multiply)           (None, 10, 100)      0           dot_9[0][0]                      
                                                                 time_distributed_1[0][0]         
__________________________________________________________________________________________________
concatenate_1 (Concatenate)     (None, 10, 200)      0           multiply_1[0][0]                 
                                                                 multiply_2[0][0]                 
__________________________________________________________________________________________________
concatenate_2 (Concatenate)     (None, 10, 200)      0           multiply_3[0][0]                 
                                                                 multiply_4[0][0]                 
__________________________________________________________________________________________________
concatenate_3 (Concatenate)     (None, 10, 200)      0           multiply_5[0][0]                 
                                                                 multiply_6[0][0]                 
__________________________________________________________________________________________________
concatenate_4 (Concatenate)     (None, 10, 900)      0           concatenate_1[0][0]              
                                                                 concatenate_2[0][0]              
                                                                 concatenate_3[0][0]              
                                                                 time_distributed_1[0][0]         
                                                                 time_distributed_2[0][0]         
                                                                 time_distributed_3[0][0]         
__________________________________________________________________________________________________
flatten_1 (Flatten)             (None, 9000)         0           concatenate_4[0][0]              
__________________________________________________________________________________________________
dropout_1 (Dropout)             (None, 9000)         0           flatten_1[0][0]                  
__________________________________________________________________________________________________
judge (Dense)                   (None, 2)            18002       dropout_1[0][0]  

I found when i input layer_name=block14_sepconv2_act(not in the above summary), no response after program execution. 
Besides, in fact  after time distributed layer, i add the attention layer,i want to konw the effect of attention layer, if i just get the heatmap of block14_sepconv2_act layer, I still don't know what happened in attention layer.

**Comment by qwertpi** [comment]
1. Keract doesn't handle submodels well so to get block14_sepconv2_act you'd need to do `get_activations(model.layers[3], x, layer_name='block14_sepconv2_act')`
2. Heatmap was designed with images and convolutional laayers in mind so won't work well on attention layers

**Comment by illith** [comment]
@qwertpi ！！！great！ thank you！！！！！！！！

**Comment by barloccia** [comment]
Sorry for repeating but i should do the same thing and I don't understand a point.
I have a network such: 
`inc = InceptionV3(
    weights='imagenet',
    include_top=False,
    pooling='max',
    input_shape=(shape[0], shape[1], 3)
    )

    for layer in inc.layers:
        layer.trainable = False

    model = Sequential()
    model.add(
            TimeDistributed(inc, input_shape=(chunk_frames, shape[0], shape[1], dataset_.n_channels))
    )
    model.add(Dropout(0.2))
    model.add(LSTM(128, activation='relu', return_sequences=False, kernel_initializer=he_uniform(), bias_initializer='zeros', dropout=0.5))
    model.add(BatchNormalization())
    model.add(Dense(4, activation='sigmoid', kernel_initializer=glorot_normal(), bias_initializer='zeros'))`

I just want to visualize the heatmaps at each time step (30 images). Is that possible?
