### ISSUE TITLE
NameError: name 'k' is not defined

### ISSUE THREAD

**Issue by danvargg** [philipperemy/keract#69]
Hi,

I've been getting below issue trying to visualize activation heatmaps . I can't seem to understand why, since as I understand is just the `channels_last` format from keras backend.

I can see that in below line of `keract.py` the K is capital and in `data_format = k.image_data_format()` is not?

https://github.com/philipperemy/keract/blob/722d2588ac588d2ef6f9832758020deba7e70b3f/keract/keract.py#L5

I didn't have an issue with `display_activations` and `first` meets what `display_heatmaps` requires as input.

Am I missing something?

``` python
first = np.array(activations.get('bAct-1/Relu:0'))
keract.display_activations(activations, save=False)
first.shape, k.image_data_format()
((1, 20, 40, 8), 'channels_last')
```

```python

keract.display_heatmaps(activations, first, save=False)

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-74-ebed9f04da1c> in <module>()
----> 1 keract.display_heatmaps(activations, first, save=False)

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keract/keract.py in display_heatmaps(activations, input_image, directory, save, fix)
    194     import math
    195 
--> 196     data_format = k.image_data_format()
    197     if fix:
    198         # fixes common errors made when passing the image

NameError: name 'k' is not defined
```

DV

**Comment by qwertpi** [comment]
> I was able to overcome the above error by capitalizing the `K` in `data_format = k.image_data_format()`, but now I'm getting.
> 
> ```python
> TypeError                                 Traceback (most recent call last)
> <ipython-input-16-ebed9f04da1c> in <module>()
> ----> 1 keract.display_heatmaps(activations, first, save=False)
> 
> ~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keract/keract.py in display_heatmaps(activations, input_image, directory, save, fix)
>     248                 # scales the activation (which will form our heat map) to be in range 0-1 using
>     249                 # the previously calculated statistics
> --> 250                 if len(img.shape) == 1:
>     251                     img = scaler.transform(img.reshape(-1, 1))
>     252                 else:
> 
> TypeError: 'tuple' object is not callable
> ```

Sorry about the problem with the capitalisation. What format is *first* in, Keract is expecting a numpy array.

**Comment by danvargg** [comment]
Thanks a lot for the response.

Here's `first`:
```python
In[35]: first.shape, len(first.shape)
Out[35]: ((1, 40, 80, 16), 4)
```

I was able to resolve the issue (manually changing `if len(img.shape()) ==...` with `if len(img.shape) ==...` to avoid the tuple error.

Now I can see the heatmaps, but then the functions split the image when mapping the heatmap.

```python
first = first.reshape(first.shape[1], first.shape[2], first.shape[3]) # Did this to remove the batch size
first.shape, len(first.shape) # ((80, 160, 1), 3)

keract.display_heatmaps(activations, first, save=False)
bAct-0/Relu:0 (1, 40, 80, 16) # Goes from (80, 160, 1) to (1, 40, 80, 16)
```

**Comment by qwertpi** [comment]
> Thanks a lot for the response.
> 
> Here's `first`:
> 
> ```python
> In[35]: first.shape, len(first.shape)
> Out[35]: ((1, 40, 80, 16), 4)
> ```
> 
> I was able to resolve the issue (manually changing `if len(img.shape()) ==...` with `if len(img.shape) ==...` to avoid the tuple error.
> 
> Now I can see the heatmaps, but then the functions split the image when mapping the heatmap.
> 
> ```python
> first = first.reshape(first.shape[1], first.shape[2], first.shape[3]) # Did this to remove the batch size
> first.shape, len(first.shape) # ((80, 160, 1), 3)
> 
> keract.display_heatmaps(activations, first, save=False)
> bAct-0/Relu:0 (1, 40, 80, 16) # Goes from (80, 160, 1) to (1, 40, 80, 16)
> ```

I can't see an `img.shape()` in your original traceback but I'm glad it's working for you now, what do you mean by "the functions split the image"?

**Comment by danvargg** [comment]
First's name is `bAct-0/Relu:0` 

Before applying `keract.display_heatmaps`:
(80, 160, 1)

After applying `keract.display_heatmaps`:

```python
keract.display_heatmaps(activations, first, save=False)
bAct-0/Relu:0 (1, 40, 80, 16) 
(40, 80)
(40, 80)
(40, 80)
(40, 80)
(40, 80)
(40, 80)
(40, 80)
(40, 80)
(40, 80)
(40, 80)
(40, 80)
(40, 80)
(40, 80)
(40, 80)
(40, 80)
(40, 80)
```

Should I keep the batch size of first?

**Comment by qwertpi** [comment]
> First's name is `bAct-0/Relu:0`
> 
> Before applying `keract.display_heatmaps`:
> (80, 160, 1)
> 
> After applying `keract.display_heatmaps`:
> 
> ```python
> keract.display_heatmaps(activations, first, save=False)
> bAct-0/Relu:0 (1, 40, 80, 16) 
> (40, 80)
> (40, 80)
> (40, 80)
> (40, 80)
> (40, 80)
> (40, 80)
> (40, 80)
> (40, 80)
> (40, 80)
> (40, 80)
> (40, 80)
> (40, 80)
> (40, 80)
> (40, 80)
> (40, 80)
> (40, 80)
> ```
> 
> Should I keep the batch size of first?

Does the image look alright? I'm fairly confident that that is just the dimensions of the activation

**Comment by danvargg** [comment]
The image is split in two.

**Comment by qwertpi** [comment]
> The image is split in two.
> 
> So half of it is shown with all the activations (8) and the other half after.

Can you upload a picture? I'm struggling to visualise what you mean

**Comment by danvargg** [comment]
Let me take a second look, the image gets downsized before that.

**Comment by danvargg** [comment]
Btw. My problem is a regression one, not classification. Is that an issue?

**Comment by philipperemy** [comment]
Problem of K corrected:

https://github.com/philipperemy/keract/commit/ce6df18d5f76f8dc69cbe611db881375bce552e2

**Comment by philipperemy** [comment]
@danvargg Did you solve your issues?

**Comment by danvargg** [comment]
Thanks for the fix. Sorry for the late reply. I did manage to do the heatmaps (reducing input image size to match the conv).

But I still can't get the heatmaps right. Here's an example with images. Last image is the heatmap.

https://github.com/danvargg/data-science/blob/master/layersVis-Copy1.ipynb

**Comment by philipperemy** [comment]
@danvargg do you think it comes from the library or from your code?

**Comment by qwertpi** [comment]
> @danvargg do you think it comes from the library or from your code?

@danvargg could you run https://github.com/philipperemy/keract/blob/master/examples/heat_map.py so we can begin to get an idea for where the issue lies

**Comment by danvargg** [comment]
Will run between today and tomorrow.

**Comment by danvargg** [comment]
It creates the cat's heatmaps with no issue.

![image](https://user-images.githubusercontent.com/13923005/68593743-227bc980-0464-11ea-8a31-643f46e9272d.png)

My model is already an `.h5` compiled model.

**Comment by philipperemy** [comment]
@danvargg I'm going to close the issue. Can you open a new one if it still does not work?

**Comment by danvargg** [comment]
yes, sorry, I just got back.

I'll try a few more things with the heatmaps, if I can't make it work will open a separate issue.

BTW, this is a really neat library, has been really helpful.

**Comment by philipperemy** [comment]
@danvargg thanks we are working hard to make a good lib :)
Good luck!!

**Comment by izainpasha** [comment]
Anyone can help with the below code error?


Code:
model = load_model(os.path.join("/content/drive/MyDrive/models", "model.h5"))
 model.summary()
 

Error:
 NameError                                 Traceback (most recent call last)
<ipython-input-5-b1e39aa78a92> in <module>()
      1 
      2 
----> 3 model = load_model(os.path.join("/content/drive/MyDrive/models", "model.h5"))
      4 model.summary()
      5 

1 frames
/usr/local/lib/python3.7/dist-packages/keras/layers/core/lambda_layer.py in get_slice(data, i, parts)
    182     if self._fn_expects_mask_arg:
    183       kwargs['mask'] = mask
--> 184     if self._fn_expects_training_arg:
    185       kwargs['training'] = training
    186 

NameError: Exception encountered when calling layer "lambda_1" (type Lambda).

name 'K' is not defined

Call arguments received:
  • inputs=tf.Tensor(shape=(None, 900, 2), dtype=float32)
  • mask=None
  • training=None

**Comment by philipperemy** [comment]
```
name 'K' is not defined
```

-> `import tensorflow.keras.backend as K`

But make sure you are using the latest code!

**Comment by izainpasha** [comment]
> make sure you are using the latest code

I've tried it but not working, I'm using the latest code with Tensorflow 1.15.2

**Comment by philipperemy** [comment]
Can you use Tensorflow 2x instead?

**Comment by fan9704** [comment]
I use tensor flow 2.8.0 also have this problem how to deal with it 
```
  File "C:\Users\cxz12\Desktop\ecg-mit-bih\src\app.py", line 32, in model_predict
    return predictByPart(data, peaks)
  File "C:\Users\cxz12\Desktop\ecg-mit-bih\src\predict.py", line 62, in predictByPart
    model = load_model('../models/MLII-latest.hdf5')
  File "C:\Users\cxz12\.virtualenvs\ecg-mit-bih-K7eoGigA\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:/Users/cxz12/Desktop/ecg-mit-bih/src/graph.py", line 52, in zeropad
    """
NameError: Exception encountered when calling layer "lambda" (type Lambda).

name 'K' is not defined

```

**Comment by ZainabSaleem13** [comment]
@fan9704 @izainpasha @philipperemy 

Hi, did anyone here manage to solve this K not defined error encountered while calling lambda layer?

**Comment by CMDTausif** [comment]
> @fan9704 @izainpasha @philipperemy
> 
> Hi, did anyone here manage to solve this K not defined error encountered while calling lambda layer?

I am facing the same problem

**Comment by philipperemy** [comment]
@CMDTausif can you add 

```
import tensorflow.keras.backend as K
```
somewhere?

Also you should probably downgrade the versions if it does not work with the latest one.
