### ISSUE TITLE
Discovering the input(s) that maximizes activation of each CNN filter

### ISSUE THREAD

**Issue by hmexx** [philipperemy/keract#71]
This isn't an issue; rather an enquiry. 

Any guidance as to how would one would use your library to find the inputs that maximize each layer/filter?

The first thought that comes to mind is to send random inputs through and measure the activations, but that doesn't feel very efficient.

**Comment by qwertpi** [comment]
You'd probably want to borrow some code from https://github.com/keras-team/keras/blob/master/examples/conv_filter_visualization.py but to be honest I wouldn't know where to start

**Comment by philipperemy** [comment]
I guess you could use the same metholody as done in:

https://christophm.github.io/interpretable-ml-book/adversarial.html.

What do you mean exactly by maximizing each layer/filter?

A Convolution output is going to be something `[batch, h, w, out_channels]`.

What do you want to maximize actually?

**Comment by qwertpi** [comment]
> I guess you could use the same metholody as done in:
> 
> https://christophm.github.io/interpretable-ml-book/adversarial.html.
> 
> What do you mean exactly by maximizing each layer/filter?
> 
> A Convolution output is going to be something `[batch, h, w, out_channels]`.
> 
> What do you want to maximize actually?

The way I see it you can either aim to get to maximise the maximum output of a specific layer(not easy to do with gradient-based methods) or you can aim to get the maximize the mean of the outputs of a specific layer (easier to do with gradient-based methods)

**Comment by philipperemy** [comment]
Let us know if you need more help! I'll close this issue for now
