### ISSUE TITLE
Sample code for text based inputs?

### ISSUE THREAD

**Issue by sarim-zafar** [philipperemy/keract#73]
Hi, I recently came across your tool and it is wonderful. I just wanted to ask if you plan on supporting text-based inputs?

**Comment by philipperemy** [comment]
Hi! Thanks a lot! Happy to hear that! There's no plan to support text-based inputs at the moment. What would you need?

**Comment by sarim-zafar** [comment]
Oh just something to visualize the importance of input tokens with respect to the prediction. I managed to write some code myself to do it.

**Comment by arthur-ver** [comment]
> Oh just something to visualize the importance of input tokens with respect to the prediction. I managed to write some code myself to do it.

Hey! Could you please give me some tips on how to implement it? With regards, Arthur
