### ISSUE TITLE
Visualize features into a CNN+LSTM for video classification

### ISSUE THREAD

**Issue by barloccia** [philipperemy/keract#82]
Hi to all, 
The network on which I am working aims to classify video sequences composed by 30 frames. Each sequence is labelled with 1 of the 4 classes considered, let's say: [0,1,2,3].
I want to use a CNN feature extraction module, then feed all the features of each image in an LSTM to predict the class. So we are talking about transfer learning: in my example the CNN is InceptionV3.
The idea is to let the last 10 layers trainable (no limits on choosing the trainable layers). I would like to visualize the features through this network. Here the simple code:
`
from keras.applications.inception_v3 import InceptionV3
from keras.layers import Dense, LSTM, TimeDistributed, Dropout
video = Input(shape=(30,299,299,3))
inc = InceptionV3(
    weights='imagenet',
    include_top=False,
    input_shape=(299, 299, 3)
)
cnn_out = GlobalAveragePooling2D()(inc.output)
cnn = Model(inputs=inc.input, outputs=cnn_out)
for layer in cnn.layers:
    layer.trainable=False
encoded_frames = TimeDistributed(cnn)(video)
encoded_sequence = LSTM(128, activation='relu', return_sequences=False, kernel_initializer=he_uniform(), bias_initializer='zeros', dropout=0.5)(encoded_frames)
hidden_layer = Dense(1024, activation='relu')(encoded_sequence)
outputs = Dense(4, activation="softmax")(hidden_layer)
model = Model(inputs=[video], outputs=outputs)

adam = Adam(lr=0.001, beta_1=0.9, beta_2=0.999, amsgrad=False)
model.compile(optimizer=adam, loss='categorical_crossentropy', metrics=['accuracy'])
`
You can try the network with any random frame generator, assign random class to each sequence.
First doubt: In the summary of the network any layer of inception appear, since INC is considered as submodel, or nested model. How can i choose which layer consider as feature visualization?
It seems that the TD wrapper just not consider the layers, or the network, before itself. Is that a correct behavior?
Second: Is your package, in general, applicable  to such a network? I would like to have an 'attention map' (I know is not) for each of the frame considered, even if the classification is done per series (return_sequences=False). Is that make sense?

Thank you very much for the help

**Comment by barloccia** [comment]
Any suggestions on this? I correctly get the activations of the network, but when i try display_heatmaps I receive the following error: TypeError: Invalid dimensions for image data.
For a single batch I have 30 frames, so the input of the network is suppose to be this one, how can I visualize results so? It's possible to have heatmaps for each time step?

**Comment by barloccia** [comment]
Ok I managed a bit the code. But now I have the following problem (that was the main one even before): My model requires 30 images as input to feed the model. If I compute the activations to some layer I receive something like (30, 299, 299, 3) which doesn't correspond to the expected input and so return 'Skipped. First dimension is not 1'. How can I visualize the heatmap to one of the images (the last one makes sense)?
I went a bit deeper in your code and it seems very well done, good work with this package!

**Comment by philipperemy** [comment]
@barloccia call the lib with just one image at a time ;)

**Comment by philipperemy** [comment]
Instead of having (30, 299, 299, 3), you should pass a tensor of shape (1, 299, 299, 3).

**Comment by barloccia** [comment]
Yes but I have some tricks. Firstly I have no direct access to the "sub-layers" of the time distributed one. In a single pass I have an input of (30, 299, 299, 3) and I would like to generate saliency map for every one of them. My idea is then to save the gradients at each time step of the LSTM. Then later on retrieve those gradients and compute grad cam. Is that makes sense? Otherwise I don't really see other solutions to compute grad cam for every image of the sequence.

**Comment by philipperemy** [comment]
The latest code should now let you access to the sub-layers (nested=True). Let me know if it solves your problem. I'll close this issue for now.
