### ISSUE TITLE
display_heatmaps does not work with single-channel prediction

### ISSUE THREAD

**Issue by jonashaag** [philipperemy/keract#84]
If your prediction results has only 1 channel, then the `.subplots()` call will not return an object that has the `.flat` attribute, so the function will fail with an `AttributeError`.

**Comment by jonashaag** [comment]
Same thing for `display_activations`. Here's some code that fixes a single layer's activation info:

```
def fix_activation_shape(acts, name):
    # Fix something else: keras layers not having implicit batch_size parameter in shape
    fixed = np.reshape(acts[name], (1, *acts[name].shape))
    # Fix this (keract#84)
    fixed = np.concatenate([fixed, fixed], axis=-1)
    return {**acts, name: fixed}
```

**Comment by philipperemy** [comment]
@jonashaag do you have an example where I can reproduce the bug?

```python
acts = {'1_channel': np.random.uniform(size=(1, 32, 32, 1))}
display_activations(acts, save=True)
```

When I run this dummy example it seems to work properly (1 channel).

Thanks!

**Comment by jonashaag** [comment]
Yes since your training data has explicit batch size. That’s not the case if you use “simple” Keras fit() syntax where batching is performed by Keras.

**Comment by philipperemy** [comment]
@jonashaag thank youu

**Comment by philipperemy** [comment]
@jonashaag you have an example? I'll close the issue otherwise.
