### ISSUE TITLE
Inner layer processing

### ISSUE THREAD

**Issue by sonfire86** [philipperemy/keract#85]
Error `the_input:0 is both fed and fetched.`

`act = get_activations(loaded_model, img)`

![image](https://user-images.githubusercontent.com/26105224/76288241-1ac01a80-62c8-11ea-8e52-856666cc0961.png)
How can I transfer inner layers if this does not work?
`[layer.name for layer in loaded_model.get_layer('efficientnet-b0').layers]`

**Comment by philipperemy** [comment]
@sonfiree it's a common problem with tensorflow

https://github.com/philipperemy/keract/blob/93b0ed54680b2679602bc70dbc304aedf9b0c8cf/keract/keract.py#L152

Here is the line that should avoid this problem.

But seems like you renamed your input to `the_input` and it did not match this criteria of `'input_' in node.name.

So easiest is for you to rename your `the_input` by `input_something_you_want` or even `the_input_`.

**Comment by sonfiree** [comment]
Im rename first layer to `the_input_`. My error 
```
InvalidArgumentError: You must feed a value for placeholder tensor 'input_1_8' with dtype float and shape [?,300,300,3]
	 [[{{node input_1_8}}]]
```

**Comment by sonfiree** [comment]
Im used `tf.keras`

**Comment by philipperemy** [comment]
@sonfiree can you share some of your code so that I can reproduce it?

It seems like you're not feeding this placeholder with data.

**Comment by sonfiree** [comment]
```
img = cv2.imread(r'533bf11d.jpg') 
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB) 
img = cv2.resize(img, (300, 300))
img = preprocess_input(img)
img = np.expand_dims(img, 0)

loaded_model.get_layer('the_input')._name = 'the_input_'
act = get_activations(loaded_model, img)
```

**Comment by philipperemy** [comment]
@sonfiree can you share more?

If I do that on my model, I would get
```
> model.get_layer('i1')._name
{AttributeError}'InputLayer' object has no attribute '_name'
```

**Comment by sonfiree** [comment]
This is all the code.

**Comment by sonfiree** [comment]
efficient-b0 has hidden layers

**Comment by philipperemy** [comment]
@sonfire86 should be fixed in Keract 4.0.0.

**Comment by sonfire86** [comment]
@philipperemy Unfortunately no. I had to manually rebuild the model

**Comment by philipperemy** [comment]
@sonfire86 so did you solve your problem?

**Comment by sonfire86** [comment]
Expanded the `Model` layers inside the main `Model` and got a large list of layers arranged one after another

**Comment by philipperemy** [comment]
Should work on the latest keract version with `nested=True`. I'm going to close this issue. Let me know!
If it still does not work provide a snippet that I can run to debug.
