### ISSUE TITLE
Display of Dense Layers

### ISSUE THREAD

**Issue by vee-upatising** [philipperemy/keract#87]
Is there a better way to display dense layers to be more visually appealing?
![dense](https://i.imgur.com/JtV4UJj.png)
All the other layers are visually clear but the layer of 256 nodes is hard to interpret.  Is there a way to reshape the visualization? Or do I need to add a reshape layer to the model?
![cnn](https://raw.githubusercontent.com/vee-upatising/Recycle-Bot/master/CNN%20Forward%20Propagation%202.gif)
This is the model I'm using:
![model](https://camo.githubusercontent.com/7a60dd23f0bc63966f33e69cb9c642a58f990cb1/68747470733a2f2f692e696d6775722e636f6d2f6e4256446a6a772e706e67)

**Comment by philipperemy** [comment]
@vee-upatising yeah that's a good question. What would you suggest here? Reshaping to a rectangle or a square shape?

**Comment by vee-upatising** [comment]
Would there be a way to change the shape to a square shape like the single output layer? Although this would be a little misleading since the nodes aren't actually arranged this way.

**Comment by philipperemy** [comment]
It works if `num_units` is a square. For example 10 would not work. So I guess something like a square of size `int(sqrt(num_units)) + 1` would make sense if `num_units` is larger than a number say 16.

**Comment by philipperemy** [comment]
@vee-upatising if you have time to write a small pr it would be appreciated!

**Comment by philipperemy** [comment]
PR: https://github.com/philipperemy/keract/pull/113

**Comment by philipperemy** [comment]
Pushed in 4.2.4
