### ISSUE TITLE
Error running keract.get_activations()

### ISSUE THREAD

**Issue by eabouzeid-sanofi** [philipperemy/keract#92]
Hi, 
I was testing Keract on my code and it had issues.  So I decide to run the sample code you provided and still has issue as you can see below. It seems something related to i1 (InvalidArgumentError: i1_1:0 is both fed and fetched.). Please advice

Code:
import numpy as np
from keras import Input, Model
from keras.layers import Dense, concatenate
from keract import get_activations

# model definition
i1 = Input(shape=(10,), name='i1')
i2 = Input(shape=(10,), name='i2')

a = Dense(1, name='fc1')(i1)
b = Dense(1, name='fc2')(i2)

c = concatenate([a, b], name='concat')
d = Dense(1, name='out')(c)
model = Model(inputs=[i1, i2], outputs=[d])

# inputs to the model
x = [np.random.uniform(size=(32, 10)), np.random.uniform(size=(32, 10))]

# call to fetch the activations of the model.
activations = get_activations(model, x, auto_compile=True)

# print the activations shapes.
[print(k, '->', v.shape, '- Numpy array') for (k, v) in activations.items()]

Error:
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
/opt/local/anaconda3/envs/Py3-ML-CUDA/lib/python3.6/site-packages/keract/keract.py in _evaluate(model, nodes_to_evaluate, x, y, auto_compile)
     44     try:
---> 45         return eval_fn(model._feed_inputs + model._feed_targets + model._feed_sample_weights)
     46     except Exception:

/opt/local/anaconda3/envs/Py3-ML-CUDA/lib/python3.6/site-packages/keract/keract.py in eval_fn(k_inputs)
     41     def eval_fn(k_inputs):
---> 42         return K.function(k_inputs, nodes_to_evaluate)(model._standardize_user_data(x, y))
     43 

/opt/local/anaconda3/envs/Py3-ML-CUDA/lib/python3.6/site-packages/tensorflow/python/keras/backend.py in __call__(self, inputs)
   2894         session != self._session):
-> 2895       self._make_callable(feed_arrays, feed_symbols, symbol_vals, session)
   2896 

/opt/local/anaconda3/envs/Py3-ML-CUDA/lib/python3.6/site-packages/tensorflow/python/keras/backend.py in _make_callable(self, feed_arrays, feed_symbols, symbol_vals, session)
   2847     # Create callable.
-> 2848     callable_fn = session._make_callable_from_options(callable_opts)
   2849     # Cache parameters corresponding to the generated callable, so that

/opt/local/anaconda3/envs/Py3-ML-CUDA/lib/python3.6/site-packages/tensorflow/python/client/session.py in _make_callable_from_options(self, callable_options)
   1482     self._extend_graph()
-> 1483     return BaseSession._Callable(self, callable_options)
   1484 

/opt/local/anaconda3/envs/Py3-ML-CUDA/lib/python3.6/site-packages/tensorflow/python/client/session.py in __init__(self, session, callable_options)
   1440             self._handle = tf_session.TF_DeprecatedSessionMakeCallable(
-> 1441                 session._session, options_ptr, status)
   1442       finally:

/opt/local/anaconda3/envs/Py3-ML-CUDA/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py in __exit__(self, type_arg, value_arg, traceback_arg)
    518             compat.as_text(c_api.TF_Message(self.status.status)),
--> 519             c_api.TF_GetCode(self.status.status))
    520     # Delete the underlying status object from memory otherwise it stays alive

InvalidArgumentError: i1:0 is both fed and fetched.

During handling of the above exception, another exception occurred:

InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-7-4a1bd5decb17> in <module>
     19 
     20 # call to fetch the activations of the model.
---> 21 activations = get_activations(model, x, auto_compile=True)
     22 
     23 # print the activations shapes.

/opt/local/anaconda3/envs/Py3-ML-CUDA/lib/python3.6/site-packages/keract/keract.py in get_activations(model, x, layer_name, nodes_to_evaluate, output_format, auto_compile)
    151     input_layer_outputs, layer_outputs = [], []
    152     [input_layer_outputs.append(node) if 'input_' in node.name else layer_outputs.append(node) for node in nodes]
--> 153     activations = _evaluate(model, layer_outputs, x, y=None, auto_compile=auto_compile)
    154 
    155     def craft_output(output_format_):

/opt/local/anaconda3/envs/Py3-ML-CUDA/lib/python3.6/site-packages/keract/keract.py in _evaluate(model, nodes_to_evaluate, x, y, auto_compile)
     45         return eval_fn(model._feed_inputs + model._feed_targets + model._feed_sample_weights)
     46     except Exception:
---> 47         return eval_fn(model._feed_inputs)
     48 
     49 

/opt/local/anaconda3/envs/Py3-ML-CUDA/lib/python3.6/site-packages/keract/keract.py in eval_fn(k_inputs)
     40 
     41     def eval_fn(k_inputs):
---> 42         return K.function(k_inputs, nodes_to_evaluate)(model._standardize_user_data(x, y))
     43 
     44     try:

/opt/local/anaconda3/envs/Py3-ML-CUDA/lib/python3.6/site-packages/tensorflow/python/keras/backend.py in __call__(self, inputs)
   2893         feed_symbols != self._feed_symbols or
   2894         session != self._session):
-> 2895       self._make_callable(feed_arrays, feed_symbols, symbol_vals, session)
   2896 
   2897     fetched = self._callable_fn(*array_vals)

/opt/local/anaconda3/envs/Py3-ML-CUDA/lib/python3.6/site-packages/tensorflow/python/keras/backend.py in _make_callable(self, feed_arrays, feed_symbols, symbol_vals, session)
   2846     callable_opts.target.append(self.updates_op.name)
   2847     # Create callable.
-> 2848     callable_fn = session._make_callable_from_options(callable_opts)
   2849     # Cache parameters corresponding to the generated callable, so that
   2850     # we can detect future mismatches and refresh the callable.

/opt/local/anaconda3/envs/Py3-ML-CUDA/lib/python3.6/site-packages/tensorflow/python/client/session.py in _make_callable_from_options(self, callable_options)
   1481     """
   1482     self._extend_graph()
-> 1483     return BaseSession._Callable(self, callable_options)
   1484 
   1485 

/opt/local/anaconda3/envs/Py3-ML-CUDA/lib/python3.6/site-packages/tensorflow/python/client/session.py in __init__(self, session, callable_options)
   1439           else:
   1440             self._handle = tf_session.TF_DeprecatedSessionMakeCallable(
-> 1441                 session._session, options_ptr, status)
   1442       finally:
   1443         tf_session.TF_DeleteBuffer(options_ptr)

/opt/local/anaconda3/envs/Py3-ML-CUDA/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py in __exit__(self, type_arg, value_arg, traceback_arg)
    517             None, None,
    518             compat.as_text(c_api.TF_Message(self.status.status)),
--> 519             c_api.TF_GetCode(self.status.status))
    520     # Delete the underlying status object from memory otherwise it stays alive
    521     # as there is a reference to status from this from the traceback due to

InvalidArgumentError: i1:0 is both fed and fetched.

**Comment by philipperemy** [comment]
@eabouzeid-sanofi which version of tensorflow/keras are you using?

**Comment by eabouzeid-sanofi** [comment]
@philipperemy 
Keras version: 2.2.4
Tensoflow version: 1.9.0

**Comment by philipperemy** [comment]
@eabouzeid-sanofi can you upgrade your keras to 2.3.x and tensorflow 2.0 or 2.1?

**Comment by philipperemy** [comment]
Let me know if the issue is still unresolved.
