### ISSUE TITLE
 tensorflow.__spec__ is None error showing when importing keract

### ISSUE THREAD

**Issue by sandeeppandey456** [philipperemy/keract#95]
I am getting the following error when I am trying to import keract -

> `Traceback (most recent call last):

  File "<ipython-input-4-ce3b394693a3>", line 2, in <module>
    from keract import get_activations

  File "/home/sandeep/anaconda3/envs/kerasenv/lib/python3.7/site-packages/keract/__init__.py", line 3, in <module>
    tf_spec = importlib.util.find_spec("tensorflow")

  File "/home/sandeep/anaconda3/envs/kerasenv/lib/python3.7/importlib/util.py", line 114, in find_spec
    raise ValueError('{}.__spec__ is None'.format(name))

ValueError: tensorflow.__spec__ is None`

I am using Keras 2.2.4 with tensorflow backend

**Comment by philipperemy** [comment]
@sandeeppandey456 which version of tensorflow are you using?

**Comment by sandeeppandey456** [comment]
Tensorflow version 1.14.0

**Comment by philipperemy** [comment]
Can you upgrade to 2.0 and try again?

**Comment by philipperemy** [comment]
Should be fixed with keract 4.0.0. Please use tensorflow 2+ if possible.
